# Generated by Django 5.2.17 on 2026-09-14 10:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک (در آدرس)')),
                ('latin_name', models.CharField(blank=True, max_length=60, verbose_name='نام لاتین')),
                ('tagline', models.CharField(max_length=200, verbose_name='شعار یک\u200cخطی')),
                ('category_label', models.CharField(blank=True, max_length=60, verbose_name='برچسب دسته (مثل MES · IoT)')),
                ('color', models.CharField(default='#1E9E7B', max_length=7, verbose_name='رنگ اختصاصی')),
                ('icon', models.CharField(default='memory', max_length=40, verbose_name='آیکن (نام Material)')),
                ('cover', models.ImageField(blank=True, upload_to='products/', verbose_name='تصویر اصلی')),
                ('logo', models.ImageField(blank=True, upload_to='products/logos/', verbose_name='لوگوی محصول')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='شرح کامل')),
                ('target_audience', models.TextField(blank=True, verbose_name='برای چه کسانی')),
                ('tech_stack', models.CharField(blank=True, help_text='مثل: Django, PostgreSQL, React', max_length=200, verbose_name='فناوری\u200cها')),
                ('catalog_pdf', models.FileField(blank=True, help_text='اگر خالی باشد، صفحه\u200cی کاتالوگ خودکار از همین اطلاعات ساخته می\u200cشود.', upload_to='products/catalogs/', verbose_name='کاتالوگ PDF (اختیاری)')),
                ('demo_url', models.URLField(blank=True, verbose_name='لینک دمو')),
                ('price_note', models.CharField(blank=True, default='قیمت بر اساس نیاز مشتری', max_length=120, verbose_name='یادداشت قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_courses', models.ManyToManyField(blank=True, related_name='products', to='academy.course', verbose_name='دوره\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان قابلیت')),
                ('text', models.TextField(blank=True, verbose_name='توضیح')),
                ('icon', models.CharField(blank=True, default='check_circle', max_length=40, verbose_name='آیکن')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'قابلیت',
                'verbose_name_plural': 'قابلیت\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='زیرنویس')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان آموزش')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='متن')),
                ('embed_html', models.TextField(blank=True, verbose_name='کد ویدیو (اختیاری)')),
                ('attachment', models.FileField(blank=True, upload_to='products/tutorials/', verbose_name='فایل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی (بدون ورود)')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.course', verbose_name='یا پیوند به دوره')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='products.product')),
            ],
            options={
                'verbose_name': 'آموزش محصول',
                'verbose_name_plural': 'آموزش\u200cهای محصول',
                'ordering': ['order', 'id'],
            },
        ),
    ]
