# Generated by Django 5.2.17 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_logo_status_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط اگر همین محتوا جای دیگری هم منتشر شده؛ معمولاً خالی.', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='عبارتی که می\u200cخواهید این صفحه با آن در گوگل پیدا شود. برای امتیاز سئو استفاده می\u200cشود.', max_length=80, verbose_name='کلیدواژه\u200cی کانونی'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='متن زیر عنوان در گوگل؛ ۱۲۰ تا ۱۶۰ کاراکتر، با کلیدواژه و دعوت به کلیک.', max_length=170, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='product',
            name='noindex',
            field=models.BooleanField(default=False, help_text='این صفحه در گوگل ایندکس نشود.', verbose_name='noindex'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوانی که در نتایج گوگل دیده می\u200cشود؛ ۵۰ تا ۶۰ کاراکتر. خالی = عنوان خود صفحه.', max_length=70, verbose_name='عنوان سئو'),
        ),
    ]
