# Generated by Django 5.2.17 on 2026-09-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='شرکت / سازمان'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('', '—'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=10, verbose_name='تحصیلات'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '—'), ('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, help_text='اختیاری — فقط برای درج روی گواهینامه', max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_certificates_publicly',
            field=models.BooleanField(default=True, verbose_name='گواهینامه\u200cها در تأیید عمومی با نام کامل نمایش داده شود'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
    ]
