# Generated by Django 5.2.17 on 2026-10-02 20:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='عنوانی که در نتایج گوگل دیده می\u200cشود؛ ۵۰ تا ۶۰ کاراکتر. خالی = عنوان خود صفحه.', max_length=70, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, help_text='متن زیر عنوان در گوگل؛ ۱۲۰ تا ۱۶۰ کاراکتر، با کلیدواژه و دعوت به کلیک.', max_length=170, verbose_name='توضیح متا')),
                ('focus_keyword', models.CharField(blank=True, help_text='عبارتی که می\u200cخواهید این صفحه با آن در گوگل پیدا شود. برای امتیاز سئو استفاده می\u200cشود.', max_length=80, verbose_name='کلیدواژه\u200cی کانونی')),
                ('canonical_url', models.URLField(blank=True, help_text='فقط اگر همین محتوا جای دیگری هم منتشر شده؛ معمولاً خالی.', verbose_name='آدرس کانونیکال')),
                ('noindex', models.BooleanField(default=False, help_text='این صفحه در گوگل ایندکس نشود.', verbose_name='noindex')),
                ('title', models.CharField(max_length=80, verbose_name='نام بازی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='نامک (در آدرس)')),
                ('engine', models.CharField(choices=[('snake', 'مار'), ('2048', '۲۰۴۸'), ('wordle-fa', 'حدس کلمات (وردل فارسی)')], max_length=12, verbose_name='موتور بازی')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='معرفی یک\u200cخطی')),
                ('how_to', models.TextField(blank=True, verbose_name='راهنمای بازی')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='توضیح کامل (زیر بازی)')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='easy', max_length=8, verbose_name='سختی')),
                ('color', models.CharField(default='#1E9E7B', max_length=7, verbose_name='رنگ')),
                ('emoji', models.CharField(default='🎮', max_length=8, verbose_name='نماد')),
                ('cover', models.ImageField(blank=True, upload_to='games/', verbose_name='تصویر')),
                ('words', models.TextField(blank=True, default='ایران\nستاره\nفرهنگ\nسلامت\nتاریخ\nریاضی\nسفارش\nمحصول\nگزارش\nتحلیل\nسیستم\nتجربه\nترجمه\nنوشته\nپرنده\nحیوان\nمدارس\nجلسات\nمهاجر\nماشین\nکاشان\nبادام\nباغچه\nپنجره\nدریچه\nمسافر\nاستاد\nمدرسه\nپارچه\nنساجی\nکارگر\nتولید\nبازار\nتجارت\nمشتری\nدیوار\nپاییز\nشکوفه\nگلدان\nشیرین\nلبخند\nدوستی\nپرواز\nکبوتر\nشاهین\nدلفین\nخرگوش\nروباه\nزرافه\nجزیره\nانگور\nنارنج\nکلوچه\nمنطقی\nماژول\nمتغیر\nامنیت\nپروژه\nطراحی\nتوسعه\nکیفیت\nبودجه\nسیاره\nباران\nطوفان\nرنگین\nنقاشی\nشاعری\nدیوان\nقصیده\nکتیبه\nسفالی\nمیراث\nفرشته\nبافتن\nگلابی\nمناره', help_text='هر خط یک کلمه\u200cی ۵ حرفی فارسی، بدون نیم\u200cفاصله و «آ». کلمه\u200cهای غیر ۵ حرفی نادیده گرفته می\u200cشوند.', verbose_name='فهرست کلمات (فقط حدس کلمات)')),
                ('leaderboard_size', models.PositiveSmallIntegerField(default=10, verbose_name='تعداد نفرات جدول امتیازات')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=40, verbose_name='نام بازیکن')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='هش IP')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='پنهان (تقلب/نام نامناسب)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game', verbose_name='بازی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
                'ordering': ['-score'],
            },
        ),
    ]
