# Generated by Django 5.2.17 on 2026-09-14 10:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('products', 'محصولات'), ('timeline', 'خط زمان کاشان'), ('academy', 'آکادمی'), ('blog', 'مقالات'), ('cta', 'فراخوان'), ('custom', 'بخش سفارشی (متن آزاد)')], max_length=20, verbose_name='نوع بخش')),
                ('kicker', models.CharField(blank=True, max_length=60, verbose_name='برچسب کوچک بالای تیتر')),
                ('title', models.CharField(max_length=150, verbose_name='تیتر')),
                ('subtitle', models.TextField(blank=True, verbose_name='زیرتیتر')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='متن (برای بخش سفارشی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('url', models.CharField(help_text='مثلاً /courses/ یا https://...', max_length=200, verbose_name='آدرس')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('new_tab', models.BooleanField(default=False, verbose_name='در تب جدید')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'منو',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک (در آدرس)')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='نمایش در فوتر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='توسعه هوشمند فرش ایرانیان', max_length=120, verbose_name='نام سایت / برند')),
                ('short_name', models.CharField(default='ICSD', max_length=40, verbose_name='نام کوتاه')),
                ('tagline', models.CharField(blank=True, default='کاشان هفت هزار سال است چیزی می\u200cسازد.', max_length=200, verbose_name='شعار')),
                ('site_url', models.URLField(default='https://icsd.ir', help_text='بدون / انتها. در sitemap و لینک\u200cهای مطلق استفاده می\u200cشود.', verbose_name='آدرس سایت')),
                ('logo', models.ImageField(blank=True, upload_to='brand/', verbose_name='لوگو')),
                ('logo_dark', models.ImageField(blank=True, upload_to='brand/', verbose_name='لوگو برای حالت شب')),
                ('favicon', models.ImageField(blank=True, upload_to='brand/', verbose_name='فاوآیکن')),
                ('founded_year', models.PositiveIntegerField(default=1396, verbose_name='سال تأسیس (شمسی)')),
                ('color_primary', models.CharField(default='#1E9E7B', max_length=7, verbose_name='رنگ اصلی')),
                ('color_accent', models.CharField(default='#16A9C7', max_length=7, verbose_name='رنگ تأکید')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='کاشان، ایران', verbose_name='آدرس')),
                ('map_embed', models.TextField(blank=True, verbose_name='کد نقشه (iframe)')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('aparat', models.URLField(blank=True, verbose_name='آپارات')),
                ('hero_title', models.CharField(default='هفت هزار سال است این شهر چیزی می\u200cسازد.', max_length=200, verbose_name='تیتر هیرو')),
                ('hero_highlight', models.CharField(default='چیزی می\u200cسازد', help_text='این عبارت داخل تیتر با گرادیان رنگی نمایش داده می\u200cشود.', max_length=80, verbose_name='بخش رنگی تیتر')),
                ('hero_subtitle', models.TextField(default='زیگورات سیلک، قنات، باغ فین، بادگیر — کاشان همیشه مهندسی کرده است. ما ادامه\u200cی همان کاریم: نرم\u200cافزار اختصاصی برای کارخانه\u200cها و بازرگانان صنعت فرش و نساجی.', verbose_name='زیرتیتر هیرو')),
                ('hero_show_clock', models.BooleanField(default=True, verbose_name='نمایش ساعت و نمایشگر')),
                ('stat_1_value', models.CharField(default='۱۳۹۶', max_length=20, verbose_name='آمار ۱ — مقدار')),
                ('stat_1_label', models.CharField(default='سال شروع، در کاشان', max_length=60, verbose_name='آمار ۱ — برچسب')),
                ('stat_2_value', models.CharField(default='۸', max_length=20, verbose_name='آمار ۲ — مقدار')),
                ('stat_2_label', models.CharField(default='محصول عملیاتی', max_length=60, verbose_name='آمار ۲ — برچسب')),
                ('stat_3_value', models.CharField(default='۵۰+', max_length=20, verbose_name='آمار ۳ — مقدار')),
                ('stat_3_label', models.CharField(default='کارخانه و بازرگانی', max_length=60, verbose_name='آمار ۳ — برچسب')),
                ('footer_text', models.TextField(blank=True, default='ارائه\u200cی خدمات جامع فناوری اطلاعات برای صنعت فرش، نساجی و بازرگانی — کاشان، ایران.', verbose_name='متن فوتر')),
                ('default_meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح متای پیش\u200cفرض')),
                ('default_og_image', models.ImageField(blank=True, upload_to='brand/', verbose_name='تصویر پیش\u200cفرض اشتراک\u200cگذاری')),
                ('head_extra_html', models.TextField(blank=True, help_text='مثلاً کد تأیید سرچ کنسول. فقط مدیر ارشد.', verbose_name='کد اضافی در head')),
                ('enamad_html', models.TextField(blank=True, verbose_name='کد اینماد')),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=64, verbose_name='مرچنت زرین\u200cپال')),
                ('zarinpal_sandbox', models.BooleanField(default=True, verbose_name='حالت آزمایشی زرین\u200cپال')),
                ('kavenegar_api_key', models.CharField(blank=True, max_length=200, verbose_name='کلید API کاوه\u200cنگار')),
                ('kavenegar_sender', models.CharField(blank=True, max_length=20, verbose_name='شماره فرستنده')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(max_length=60, verbose_name='دوره / سال')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='توضیح')),
                ('color', models.CharField(default='#1E9E7B', max_length=7, verbose_name='رنگ نقطه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رویداد خط زمان',
                'verbose_name_plural': 'خط زمان کاشان',
                'ordering': ['order', 'id'],
            },
        ),
    ]
