# Generated by Django 5.2.17 on 2026-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_particles',
            field=models.BooleanField(default=True, help_text='کلمه\u200cها از ذره ساخته می\u200cشوند، یکی\u200cیکی به هم تبدیل می\u200cشوند و با ماوس/لمس پراکنده می\u200cشوند.', verbose_name='کلمات ذره\u200cای متحرک'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_words',
            field=models.CharField(default='ایده|داده|هوش مصنوعی|نرم\u200cافزار', help_text='با | جدا کنید. بهتر است کوتاه باشند (۱ یا ۲ کلمه).', max_length=200, verbose_name='کلمات ذره\u200cای'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_words_interval',
            field=models.PositiveSmallIntegerField(default=3200, verbose_name='مکث هر کلمه (میلی\u200cثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_words_logo',
            field=models.BooleanField(default=True, help_text='بعد از آخرین کلمه، لوگوی شرکت از ذره\u200cها ساخته شود.', verbose_name='پایان با لوگو'),
        ),
    ]
