# Generated by Django 5.2.17 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_home_sections_new_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط اگر همین محتوا جای دیگری هم منتشر شده؛ معمولاً خالی.', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AddField(
            model_name='page',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='عبارتی که می\u200cخواهید این صفحه با آن در گوگل پیدا شود. برای امتیاز سئو استفاده می\u200cشود.', max_length=80, verbose_name='کلیدواژه\u200cی کانونی'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='متن زیر عنوان در گوگل؛ ۱۲۰ تا ۱۶۰ کاراکتر، با کلیدواژه و دعوت به کلیک.', max_length=170, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False, help_text='این صفحه در گوگل ایندکس نشود.', verbose_name='noindex'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوانی که در نتایج گوگل دیده می\u200cشود؛ ۵۰ تا ۶۰ کاراکتر. خالی = عنوان خود صفحه.', max_length=70, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='indexnow_key',
            field=models.CharField(blank=True, help_text='اختیاری؛ ۸ تا ۶۴ حرف و عدد. خالی = غیرفعال.', max_length=64, verbose_name='کلید IndexNow'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='key',
            field=models.CharField(choices=[('sialk', 'منظره\u200cی تپه سیلک (نوار تمام\u200cعرض)'), ('band', 'نوار نقش سفال'), ('products', 'محصولات'), ('customers', 'مشتریان'), ('team', 'تیم'), ('timeline', 'خط زمان کاشان'), ('academy', 'آکادمی'), ('blog', 'مقالات'), ('cta', 'فراخوان'), ('custom', 'بخش سفارشی (متن آزاد)')], max_length=20, verbose_name='نوع بخش'),
        ),
    ]
