# Generated by Django 5.2.17 on 2026-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_canonical_url_page_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='key',
            field=models.CharField(choices=[('sialk', 'منظره\u200cی تپه سیلک (نوار تمام\u200cعرض)'), ('band', 'نوار نقش سفال'), ('products', 'محصولات'), ('customers', 'مشتریان'), ('team', 'تیم'), ('timeline', 'خط زمان کاشان'), ('academy', 'آکادمی'), ('blog', 'مقالات'), ('library', 'کتابخانه دیجیتال'), ('games', 'بازی\u200cها'), ('cta', 'فراخوان'), ('custom', 'بخش سفارشی (متن آزاد)')], max_length=20, verbose_name='نوع بخش'),
        ),
    ]
