# Generated by Django 5.2.17 on 2026-09-14 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت / کارخانه')),
                ('job_title', models.CharField(blank=True, max_length=80, verbose_name='سمت')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('topic', models.CharField(choices=[('mes', 'اتوماسیون خط تولید / MES'), ('erp', 'ERP و برنامه\u200cریزی'), ('cmms', 'نگهداری و تعمیرات'), ('web', 'وب\u200cسایت / فروشگاه'), ('app', 'اپلیکیشن موبایل'), ('ai', 'هوش مصنوعی / تحلیل داده'), ('training', 'آموزش سازمانی'), ('other', 'سایر')], default='other', max_length=12, verbose_name='موضوع')),
                ('budget', models.CharField(blank=True, choices=[('', 'مشخص نیست'), ('lt50', 'کمتر از ۵۰ میلیون'), ('50-150', '۵۰ تا ۱۵۰ میلیون'), ('150-500', '۱۵۰ تا ۵۰۰ میلیون'), ('gt500', 'بیش از ۵۰۰ میلیون')], max_length=10, verbose_name='بودجه\u200cی تقریبی')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مناسب برای جلسه')),
                ('description', models.TextField(verbose_name='شرح نیاز')),
                ('attachment', models.FileField(blank=True, upload_to='leads/', verbose_name='فایل پیوست')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('meeting', 'جلسه'), ('proposal', 'پیشنهاد ارسال شد'), ('won', 'قرارداد بسته شد'), ('lost', 'منتفی')], default='new', max_length=12, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پیگیری')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.city', verbose_name='شهر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='محصول مورد نظر')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'درخواست پروژه',
                'verbose_name_plural': 'درخواست\u200cهای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='leads.province', verbose_name='استان'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name')},
        ),
    ]
