# Generated by Django 5.2.17 on 2026-09-14 10:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('icon', models.CharField(blank=True, default='school', max_length=40, verbose_name='آیکن (نام Material)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دوره',
                'verbose_name_plural': 'دسته\u200cبندی دوره\u200cها',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان درس')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, verbose_name='نامک')),
                ('kind', models.CharField(choices=[('text', 'متنی'), ('video', 'ویدیویی')], default='text', max_length=8, verbose_name='نوع')),
                ('minutes', models.PositiveSmallIntegerField(default=10, verbose_name='مدت (دقیقه)')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='متن درس')),
                ('video_source', models.CharField(choices=[('none', 'بدون ویدیو'), ('arvan', 'آروان VOD'), ('aparat', 'آپارات / کد جاسازی'), ('upload', 'فایل آپلودشده')], default='none', max_length=8, verbose_name='منبع ویدیو')),
                ('arvan_video_id', models.CharField(blank=True, help_text='آدرس کامل Player URL از پنل آروان VOD', max_length=300, verbose_name='آدرس پلیر آروان')),
                ('embed_html', models.TextField(blank=True, verbose_name='کد جاسازی (آپارات و ...)')),
                ('video_file', models.FileField(blank=True, upload_to='lessons/videos/', verbose_name='فایل ویدیو')),
                ('attachment', models.FileField(blank=True, upload_to='lessons/files/', verbose_name='فایل پیوست (کد، اسلاید)')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیشرفت درس',
                'verbose_name_plural': 'پیشرفت درس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فصل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک (در آدرس)')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=12, verbose_name='سطح')),
                ('summary', models.CharField(max_length=250, verbose_name='خلاصه\u200cی یک\u200cخطی')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='شرح کامل')),
                ('cover', models.ImageField(blank=True, upload_to='courses/', verbose_name='تصویر')),
                ('price', models.PositiveIntegerField(default=0, help_text='۰ یعنی رایگان', verbose_name='قیمت (تومان)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت کل (دقیقه)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه (نمایش در صفحه اصلی)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academy.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
