# Generated by Django 5.2.17 on 2026-09-14 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('explanation', models.TextField(blank=True, verbose_name='توضیح پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'سؤال\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('question_ids', models.JSONField(default=list, verbose_name='سؤال\u200cهای این نوبت')),
                ('answers', models.JSONField(default=dict, verbose_name='پاسخ\u200cها')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='نمره (درصد)')),
                ('passed', models.BooleanField(default=False, verbose_name='قبول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوبت آزمون',
                'verbose_name_plural': 'نوبت\u200cهای آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد')),
                ('serial', models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره')),
                ('full_name', models.CharField(max_length=160, verbose_name='نام روی گواهی')),
                ('score', models.PositiveSmallIntegerField(verbose_name='نمره')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='ابطال شده')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='academy.attempt', verbose_name='نوبت آزمون')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academy.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='درست')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='academy.question')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('pass_percent', models.PositiveSmallIntegerField(default=70, verbose_name='درصد قبولی')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=20, verbose_name='مهلت (دقیقه)')),
                ('questions_per_attempt', models.PositiveSmallIntegerField(default=0, help_text='۰ یعنی همه\u200cی سؤال\u200cها', verbose_name='تعداد سؤال هر نوبت')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='۰ یعنی نامحدود', verbose_name='حداکثر نوبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('show_explanations', models.BooleanField(default=True, verbose_name='نمایش توضیح پاسخ\u200cها بعد از آزمون')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='academy.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.quiz'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.quiz', verbose_name='آزمون'),
        ),
    ]
