# Generated by Django 5.2.17 on 2026-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='بدون دامنه. مثل /category/ai/', max_length=300, unique=True, verbose_name='مسیر قدیمی')),
                ('new_path', models.CharField(blank=True, help_text='خالی = ۴۱۰ (حذف شده)', max_length=300, verbose_name='مسیر جدید')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 دائمی'), (302, '302 موقت'), (410, '410 حذف شده')], default=301, verbose_name='کد')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ریدایرکت',
                'verbose_name_plural': 'ریدایرکت\u200cها',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='با / شروع و تمام شود. مثل /courses/django/', max_length=300, unique=True, verbose_name='مسیر')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان (title)')),
                ('description', models.CharField(blank=True, max_length=320, verbose_name='توضیح (meta description)')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='کلیدواژه\u200cها')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='تصویر اشتراک\u200cگذاری')),
                ('canonical', models.URLField(blank=True, verbose_name='آدرس کانونیکال')),
                ('noindex', models.BooleanField(default=False, verbose_name='noindex (از ایندکس خارج شود)')),
                ('schema_json', models.TextField(blank=True, help_text='اختیاری؛ یک آبجکت JSON معتبر.', verbose_name='JSON-LD اضافی')),
            ],
            options={
                'verbose_name': 'متادیتای صفحه',
                'verbose_name_plural': 'متادیتای صفحات',
                'ordering': ['path'],
            },
        ),
    ]
