# Generated by Django 5.2.17 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True, verbose_name='مسیر')),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('referrer', models.CharField(blank=True, max_length=300, verbose_name='آخرین ارجاع\u200cدهنده')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='اولین بار')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بار')),
                ('redirect_to', models.CharField(blank=True, help_text='مثلاً /blog/  — با ذخیره، ریدایرکت ۳۰۱ ساخته و این ردیف حل\u200cشده علامت می\u200cخورد.', max_length=300, verbose_name='ریدایرکت به')),
                ('resolved', models.BooleanField(default=False, verbose_name='حل شده')),
            ],
            options={
                'verbose_name': 'خطای ۴۰۴',
                'verbose_name_plural': 'نمایشگر ۴۰۴',
                'ordering': ['resolved', '-hits'],
            },
        ),
    ]
