# Generated by Django 5.2.17 on 2026-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_notfoundlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(help_text='بدون دامنه. مثل /category/ai/ — با * در انتها (مثل /tutorials/django/*) همه\u200cی زیرمسیرها ریدایرکت می\u200cشوند.', max_length=300, unique=True, verbose_name='مسیر قدیمی'),
        ),
    ]
