# Generated by Django 5.2.17 on 2026-10-02 19:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='عنوانی که در نتایج گوگل دیده می\u200cشود؛ ۵۰ تا ۶۰ کاراکتر. خالی = عنوان خود صفحه.', max_length=70, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, help_text='متن زیر عنوان در گوگل؛ ۱۲۰ تا ۱۶۰ کاراکتر، با کلیدواژه و دعوت به کلیک.', max_length=170, verbose_name='توضیح متا')),
                ('focus_keyword', models.CharField(blank=True, help_text='عبارتی که می\u200cخواهید این صفحه با آن در گوگل پیدا شود. برای امتیاز سئو استفاده می\u200cشود.', max_length=80, verbose_name='کلیدواژه\u200cی کانونی')),
                ('canonical_url', models.URLField(blank=True, help_text='فقط اگر همین محتوا جای دیگری هم منتشر شده؛ معمولاً خالی.', verbose_name='آدرس کانونیکال')),
                ('noindex', models.BooleanField(default=False, help_text='این صفحه در گوگل ایندکس نشود.', verbose_name='noindex')),
                ('name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, help_text='مثل itwman → /team/itwman/', unique=True, verbose_name='نامک (در آدرس)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='نام لاتین')),
                ('role', models.CharField(max_length=120, verbose_name='سمت')),
                ('role_en', models.CharField(blank=True, max_length=120, verbose_name='سمت (لاتین)')),
                ('degree', models.CharField(blank=True, help_text='مثل کارشناسی ارشد', max_length=60, verbose_name='آخرین مدرک')),
                ('photo', models.ImageField(blank=True, help_text='مربع، دست\u200cکم ۴۰۰×۴۰۰ پیکسل.', upload_to='team/', verbose_name='تصویر')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='درباره')),
                ('birth_year', models.CharField(blank=True, max_length=4, verbose_name='سال تولد')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='محل سکونت')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('show_contact', models.BooleanField(default=True, help_text='ایمیل و تلفن در صفحه\u200cی رزومه نمایش داده شود.', verbose_name='نمایش اطلاعات تماس')),
                ('show_birth_year', models.BooleanField(default=True, verbose_name='نمایش سال تولد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('label', models.CharField(help_text='LinkedIn، GitHub، Telegram، ...', max_length=40, verbose_name='نام شبکه')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='team.teammember')),
            ],
            options={
                'verbose_name': 'شبکه\u200cی اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('group', models.CharField(blank=True, help_text='مثل Programming، CMS، Graphic', max_length=60, verbose_name='گروه')),
                ('name', models.CharField(max_length=80, verbose_name='مهارت')),
                ('level', models.PositiveSmallIntegerField(default=70, verbose_name='سطح (٪)')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='team.teammember')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, verbose_name='پیوند')),
                ('authors', models.CharField(blank=True, max_length=300, verbose_name='همکاران')),
                ('venue', models.CharField(blank=True, max_length=300, verbose_name='کنفرانس / نشریه')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='team.teammember')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=200, verbose_name='سمت')),
                ('org', models.CharField(blank=True, max_length=200, verbose_name='سازمان • شهر')),
                ('start', models.CharField(blank=True, max_length=10, verbose_name='از سال')),
                ('end', models.CharField(blank=True, help_text='خالی یا «تاکنون»', max_length=10, verbose_name='تا سال')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='team.teammember')),
            ],
            options={
                'verbose_name': 'سابقه\u200cی کاری',
                'verbose_name_plural': 'سوابق کاری',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('title', models.CharField(help_text='مثل کارشناسی ارشد - مهندسی کامپیوتر - نرم\u200cافزار', max_length=200, verbose_name='مقطع و رشته')),
                ('org', models.CharField(blank=True, max_length=200, verbose_name='دانشگاه / مؤسسه')),
                ('start', models.CharField(blank=True, max_length=10, verbose_name='از سال')),
                ('end', models.CharField(blank=True, max_length=10, verbose_name='تا سال')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='پایان\u200cنامه / توضیح')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='team.teammember')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
