# Generated by Django 5.2.17 on 2026-09-14 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='مسیر')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('referrer', models.CharField(blank=True, max_length=300, verbose_name='ارجاع\u200cدهنده')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('device', models.CharField(blank=True, max_length=10, verbose_name='دستگاه')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='هش IP')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
